<template>
  <div class="loadingio-spinner-ellipsis-upng05di5eb">
    <div class="ldio-eq4lslp6pkq">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style type="text/css">
@keyframes ldio-eq4lslp6pkq {
  0% {
    transform: translate(12px, 80px) scale(0);
  }
  25% {
    transform: translate(12px, 80px) scale(0);
  }
  50% {
    transform: translate(12px, 80px) scale(1);
  }
  75% {
    transform: translate(80px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(1);
  }
}
@keyframes ldio-eq4lslp6pkq-r {
  0% {
    transform: translate(148px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(0);
  }
}
@keyframes ldio-eq4lslp6pkq-c {
  0% {
    background: #e15b64;
  }
  25% {
    background: #abbd81;
  }
  50% {
    background: #f8b26a;
  }
  75% {
    background: #f47e60;
  }
  100% {
    background: #e15b64;
  }
}
.ldio-eq4lslp6pkq div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px, 80px) scale(1);
  background: #e15b64;
  animation: ldio-eq4lslp6pkq 1s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-eq4lslp6pkq div:nth-child(1) {
  background: #f47e60;
  transform: translate(148px, 80px) scale(1);
  animation: ldio-eq4lslp6pkq-r 0.25s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-eq4lslp6pkq-c 1s infinite step-start;
}
.ldio-eq4lslp6pkq div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e15b64;
}
.ldio-eq4lslp6pkq div:nth-child(3) {
  animation-delay: -0.5s;
  background: #f47e60;
}
.ldio-eq4lslp6pkq div:nth-child(4) {
  animation-delay: -0.75s;
  background: #f8b26a;
}
.ldio-eq4lslp6pkq div:nth-child(5) {
  animation-delay: -1s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-upng05di5eb {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-eq4lslp6pkq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-eq4lslp6pkq div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
