# Create a CI for Vue App with Cypress Test
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Move to project directory
          run: cd project

      - name: Install dependencies
          run: npm ci

      - name: Build
          run: npm run build

      - name: Run server
          run: npm run serve


